version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: social-postgres

    restart: unless-stopped

    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements

    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: social-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: social-backend

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy


    ports:
      - "8080:8080"

    environment:

      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/social
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

volumes:

  postgres_data:

  redis_data: