spring.application.name=social

# ================= DATABASE =================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SocialDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong!Pass123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ================= SWAGGER =================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ================= SECURITY FIX =================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ================= JWT =================
jwt.secret=${JWT_SECRET:THANGNAOBIETTOKENNAYTHITAOCUNCHIU}
jwt.access-expiration=900000
jwt.refresh-expiration=7

cloudinary.cloud-name=dousreizx
cloudinary.api-key=671278485776239
cloudinary.api-secret=twUASMiDFH4Hqo7tZZloQ4g-JQc